### ISSUE TITLE
What the chinese data were used for SFT?

### ISSUE THREAD

**Issue by bmkor** [ycjcl868/Gemma-1.1-7B-Chinese-Chat#1]
Thank you for sharing out this wonderful fine-tuned model.

As title, mind sharing us a bit on the information of the chinese data used for SFT?

**Comment by ycjcl868** [comment]
https://huggingface.co/datasets/silk-road/alpaca-data-gpt4-chinese
https://huggingface.co/datasets/hfl/ruozhiba_gpt4
https://huggingface.co/datasets/YeungNLP/firefly-train-1.1M
